# Generated by Django 2.0 on 2017-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '管理员表',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val', models.IntegerField(blank=True, null=True, verbose_name='打分题对应答案')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='建议题对应答案')),
            ],
            options={
                'verbose_name_plural': '答案表',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='选项标题')),
                ('score', models.IntegerField(verbose_name='选项分数')),
            ],
            options={
                'verbose_name_plural': '问题选项表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=16, verbose_name='部门名称')),
            ],
            options={
                'verbose_name_plural': '部门表',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('department', models.ForeignKey(on_delete=True, to='survey.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=256, verbose_name='问题内容')),
                ('question_type', models.IntegerField(choices=[(1, '单选'), (2, '多选'), (3, '打分'), (4, '建议')], verbose_name='问题类型')),
            ],
            options={
                'verbose_name_plural': '问题表',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='问卷标题')),
                ('description', models.CharField(max_length=512, verbose_name='问卷描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('admin', models.ForeignKey(on_delete=True, to='survey.Admin', verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=True, to='survey.Department', verbose_name='接受调查的部门')),
            ],
            options={
                'verbose_name_plural': '问卷表',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=True, to='survey.Questionnaire', verbose_name='所属问卷'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=True, to='survey.Question', verbose_name='所属问题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='survey.Choice', verbose_name='选择题对应选项'),
        ),
        migrations.AddField(
            model_name='answer',
            name='employee',
            field=models.ForeignKey(on_delete=True, to='survey.Employee', verbose_name='回答员工'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=True, to='survey.Question', verbose_name='对应问题'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('employee', 'question')},
        ),
    ]
